### ISSUE TITLE
Powered Detector Rail can only launch minecarts in certain directions

### ISSUE THREAD

**Issue by Hiyshhiysh** [Kipama/Modern_Minecarts#22]
I seem to only be able to place the powered detector rail in the positive X direction and the negative Z direction, meaning the minecart can only be launched in those directions. Relatively small issue but still quite annoying.

Using 1.1.0 for 1.20.1.

**Comment by Kipama** [comment]
Hi, you should be able to shift+right click the rail once placed, to turn it 180°.
Please let me know if this works or not, so I can close the issue or look into it otherwise.

**Comment by Hiyshhiysh** [comment]
Ah yep, that worked! It may be worth putting a note under the item to make it clearer how to reverse it, but thanks for the response anyway!
